"""add nullable qr_code

Revision ID: 293bb4f35221
Revises: 458eb9e3dcb7
Create Date: 2026-06-04 09:10:50.840085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293bb4f35221'
down_revision = '458eb9e3dcb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('qr_code',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('qr_code',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
