"""remove rsvp as seperate entity

Revision ID: 458eb9e3dcb7
Revises: a5481b56b117
Create Date: 2026-06-04 07:20:39.538693

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "458eb9e3dcb7"
down_revision = "a5481b56b117"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rsvps")
    op.drop_table("dict_rsvp_statuses")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rsvps",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("status_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("event_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("rsvps_event_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["status_id"], ["dict_rsvp_statuses.id"], name=op.f("rsvps_status_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("rsvps_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("rsvps_pkey")),
    )
    op.create_table(
        "dict_rsvp_statuses",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=80), autoincrement=False, nullable=False
        ),
        sa.Column("is_terminal", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("rsvp_statuses_pkey")),
    )
    # ### end Alembic commands ###
